// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRqTNp7TEbUh58kk6hPRZqjH33DpEcuA0',
    appId: '1:53845704015:web:616523ac2bf6dfab48593a',
    messagingSenderId: '53845704015',
    projectId: 'project-fpb201',
    authDomain: 'project-fpb201.firebaseapp.com',
    databaseURL: 'https://project-fpb201-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-fpb201.appspot.com',
    measurementId: 'G-LNZ8QJCRDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkrz9vLYn8DTu7mPNSwguvl1Vpn62IqfM',
    appId: '1:53845704015:android:f17b270c30ab517b48593a',
    messagingSenderId: '53845704015',
    projectId: 'project-fpb201',
    databaseURL: 'https://project-fpb201-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-fpb201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLQ1yT87Lft814q7nPNCoZhWTNVOoxSgE',
    appId: '1:53845704015:ios:bc9e47758e82ff4d48593a',
    messagingSenderId: '53845704015',
    projectId: 'project-fpb201',
    databaseURL: 'https://project-fpb201-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-fpb201.appspot.com',
    iosClientId: '53845704015-lbidedg8mbqg6m5hom9ff7kh1fda7h24.apps.googleusercontent.com',
    iosBundleId: 'com.example.cobaUlang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLQ1yT87Lft814q7nPNCoZhWTNVOoxSgE',
    appId: '1:53845704015:ios:bc9e47758e82ff4d48593a',
    messagingSenderId: '53845704015',
    projectId: 'project-fpb201',
    databaseURL: 'https://project-fpb201-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-fpb201.appspot.com',
    iosClientId: '53845704015-lbidedg8mbqg6m5hom9ff7kh1fda7h24.apps.googleusercontent.com',
    iosBundleId: 'com.example.cobaUlang',
  );
}
